services:
    app:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
            - redis
        networks:
            - laravel_network

    queue-worker:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-queue-worker
        working_dir: /var/www/html
        command: sh -c "php artisan queue:work redis --verbose"
        depends_on:
            - app
            - redis
        networks:
            - laravel_network

    scheduler:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-scheduler
        working_dir: /var/www/html
        command: sh -c "php artisan schedule:work"
        depends_on:
            - app
            - redis
        networks:
            - laravel_network


    db:
        image: mysql:8.0
        container_name: mysql-db
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: finance_tool
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: user
            MYSQL_PASSWORD: Pass1234!
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - laravel_network

    redis:
        restart: always
        image: redis:7
        container_name: redis-cache
        ports:
            - "6379:6379"
        networks:
            - laravel_network

networks:
    laravel_network:
        driver: bridge

volumes:
    db-data:
